backend:
  name: github
  repo: wrick17/pogo

media_folder: static/assets

collections:
  - name: blogs
    label: Blogs
    label_singular: Blog
    folder: blogs
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: tags
    label: Tags
    label_singular: tag
    folder: tags
    create: true
    fields:
      - { name: value, label: Value }
      - { name: label, label: Label }